### ISSUE TITLE
Provide additional data and setup instructions for local users

### ISSUE THREAD

**Issue by samnooij** [carpentries-lab/metagenomics-analysis#70]
Thank you for sharing this awesome lesson material! I'm preparing to teach this workshop as an instructor and I'm running into a little issue. I'm going to teach the final part with RStudio. Therefore, I need the Kraken BIOM file as input. Also, I do not have the AWS virtual machine available right now, so I'm working on my PC. This is where I needed to get creative.

First, I could not find the Kraken output file, so I decided to run that myself. Then, I found that there were no installation instructions for Kraken (and kraken-biom!). I ended up installing all software using the conda YAML file copied at the bottom. (I used the Kraken database linked in the lesson material: `ftp://ftp.ccb.jhu.edu/pub/data/kraken2_dbs/old/minikraken2_v2_8GB_201904.tgz`.)
Then I tried as input both the subsampled files from `sub.tar.gz` on https://figshare.com/articles/dataset/Data_Carpentry_Genomics_beta_2_0/7726454 and the untrimmed reads from `backup.tar.gz`. Neither of these allows me to produce results in R identical to the lesson material. (But it does work and I can run the R commands!) Would it be possible to share the BIOM file and/or the actual input data used to create the output as shown in the lessons? And maybe add a little more instructions for the 'do it yourself users'? Thanks in advance!

```yaml
name: metagenomics-workshop

channels:
 - bioconda
 - conda-forge
 - defaults

dependencies:
 - fastqc=0.11.7
 - trimmomatic=0.38
 - bwa=0.7.17
 - samtools=1.9
 - bcftools=1.9
 - kraken2=2.1.2
 - kraken-biom=1.2.0
```
